### ISSUE TITLE
Running through Dockerfile broken

### ISSUE THREAD

**Issue by VHellendoorn** [EleutherAI/gpt-neox#419]
**Describe the bug**
When using an image based on the provided `Dockerfile` and running the quick start steps (download enron data, run `deep.py`), execution crashes before training begins.

**To Reproduce**
1. Build an image using the provided Dockerfile
2. Run said image, mounting 8 RTX800 GPUs
3. Fetch enron data using the `prepare_dataset.py` script
4. Run `./deepy.py pretrain_gpt2.py -d configs small.yml local_configs.yml`
5. The code crashes with a non-descript `NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:825, unhandled system error, NCCL version 2.7.8`

**Expected behavior**
Training starts or a specific error is provided.

**Proposed solution**
The NCCL error is typically a stand-in for a real issue that is not relayed back through multiprocessing. As a first step, it would be nice to know if this setup works out-of-the-box for others; in that case, it might be my resources or CUDA version.

**Environment (please complete the following information):**
 - GPUs: 8 RTX8000 GPUs
- Configs: Ubuntu 20.04, Cuda 11.2

**Additional context**

**Comment by StellaAthena** [comment]
Based on [this issue](https://github.com/PyTorchLightning/pytorch-lightning/issues/4420) I would try downgrading to pytorch 1.6 and cuda 10.2. It seems that the problem is GPU-specific and I do not have access to a RTX8000 for testing unfortunately.

**Comment by VHellendoorn** [comment]
Thanks for your quick responses. I did dig into that linked issue thread a bit, but no luck with the fixes proposed there.

@EricHallahan, I was referring to the output of `nvcc --version` within the container, which on a second look is 11.1 (not 11.2), my apologies. The specific build is `cuda_11.1.TC455_06.29190527_0`, so I'm guessing driver version 455.06. This is all run through an [nvidia-docker backed container](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html) (version 2.6.0-1) on Linux; the driver/CUDA version in the host OS is 450.142 / 11.0, but I suspect that discrepancy doesn't play a role. No changes were made to the code and nothing else was installed in the container.

The container did prompt me to run that `python` command the first time I ran `deep.py`, and installing that seemed to have been successful. So the full chain of commands is:

```bash
git clone https://github.com/EleutherAI/gpt-neox && cd gpt-neox
docker build -t gptneox -f Dockerfile .
docker run --rm -it --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 --mount type=bind,src=$PWD,dst=/gpt-neox gptneox
# Inside the container
cd /gpt-neox
sudo python3 prepare_data.py
sudo python /gpt-neox/megatron/fused_kernels/setup.py install
sudo ./deepy.py pretrain_gpt2.py -d configs small.yml local_setup.yml
```

**Comment by EricHallahan** [comment]
Can you run it again with `NCCL_DEBUG=WARN`?

**Comment by VHellendoorn** [comment]
Actuall, would it help if I submit a PR documenting the "Using Docker" steps? Happy to add something to the README.

**Comment by PyxAI** [comment]
> That worked! Adding `–shm-size=1g –ulimit memlock=-1` to the `nvidia-docker run` (for others: note that this won't work with `docker run --runtime=nvidia`) command solved it. The default shared memory was 64MB, which is evidently far too little.
> 
> Thanks so much for your help!

That worked for me too
Just want to mention that the dashes in the command here needs to be replaced -shm-size=1g -ulimit memlock=-1
– != -
