### ISSUE TITLE
CUDA Out of Memory for 20B Model on 2 A100 40GB GPUs

### ISSUE THREAD

**Issue by seeEssex** [EleutherAI/gpt-neox#606]
Hi, I am attempting to finetune the 20B model, using the provided `configs/20B.yaml` edited with the settings as followed:
- Dropping `pipe-parallel-size` to 1
- Adding `finetune=true` 
- Dropping `train_micro_batch_size_per_gpu` to 1

```
{
  # Tokenizer /  checkpoint settings - you will need to change these to the location you have them saved in
  "vocab-file": "./20B_checkpoints/20B_tokenizer.json",
  "save": "./20B_checkpoints",
  "load": "./20B_checkpoints",

  # If finetuning, edit the following to the location of your finetuning dataset:
  "data-path": "./data/pile_20B_tokenizer/pile_20B_tokenizer_text_document",

  "finetune": true,

  # parallelism settings ( you will want to change these based on your cluster setup, ideally scheduling pipeline stages
  # across the node boundaries )
  "pipe-parallel-size": 1,
  "model-parallel-size": 2,

  # model settings
  "num-layers": 44,
  "hidden-size": 6144,
  "num-attention-heads": 64,
  "seq-length": 2048,
  "max-position-embeddings": 2048,
  "norm": "layernorm",
  "pos-emb": "rotary",
  "rotary_pct": 0.25,
  "no-weight-tying": true,
  "gpt_j_residual": true,
  "output_layer_parallelism": "column",
  "scaled-upper-triang-masked-softmax-fusion": true,
  "bias-gelu-fusion": true,

  # init methods
  "init_method": "small_init",
  "output_layer_init_method": "wang_init",

  # optimizer settings
  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 0.97e-4,
      "betas": [0.9, 0.95],
      "eps": 1.0e-8,
      }
      },

  "min_lr": 0.97e-5,
  "zero_optimization": {
  "stage": 1,
  "allgather_partitions": True,
  "allgather_bucket_size": 1260000000,
  "overlap_comm": True,
  "reduce_scatter": True,
  "reduce_bucket_size": 1260000000,
  "contiguous_gradients": True,
  "cpu_offload": False
  },

  # batch / data settings (assuming 96 GPUs)
  "train_micro_batch_size_per_gpu": 1,
  "gradient_accumulation_steps": 32,
  "data-impl": "mmap",
  "split": "995,4,1",

  # activation checkpointing
  "checkpoint-activations": true,
  "checkpoint-num-layers": 1,
  "partition-activations": false,
  "synchronize-each-layer": true,

  # regularization
  "gradient_clipping": 1.0,
  "weight-decay": 0.01,
  "hidden-dropout": 0,
  "attention-dropout": 0,

  # precision settings
  "fp16": {
    "fp16": true,
    "enabled": true,
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "initial_scale_power": 12,
    "hysteresis": 2,
    "min_loss_scale": 1
    },

  # misc. training settings
  "train-iters": 150000,
  "lr-decay-iters": 150000,

  "distributed-backend": "nccl",
  "lr-decay-style": "cosine",
  "warmup": 0.01,
  "save-interval": 500,
  "eval-interval": 1000,
  "eval-iters": 10,

  # logging
  "log-interval": 2,
  "steps_per_print": 2,
  "wall_clock_breakdown": false,

  ### NEW DATA: ####
  "tokenizer_type": "HFTokenizer",
  "tensorboard-dir": "./tensorboard",
  "log-dir": "./logs",

}
```
However, I am getting OOM with `RuntimeError: CUDA out of memory. Tried to allocate 21.12 GiB (GPU 1; 39.59 GiB total capacity; 21.13 GiB already allocated; 16.80 GiB free; 21.13 GiB reserved in total by PyTorch)` on each of the GPUs. 

Attempting with 4 A100 GPUs does not seem to spread the memory usage across them, as I am still seeing around 21GB attempted to be allocated on each of them.

I probably missed something here, so would like to seek advice on how I may bring down the memory usage on each GPU.

Thanks!

**Comment by StellaAthena** [comment]
Why are you using Pipeline Parallel = 1?

**Comment by seeEssex** [comment]
I was referring to the README [here](https://github.com/EleutherAI/gpt-neox#using-a-pretrained-model), and initially tried with pipeline parallel = 2 for 4 GPUs. Then I would get the following OOM error for each of the 4 GPUs.
```
RuntimeError: CUDA out of memory. Tried to allocate 4.70 GiB (GPU 0; 39.59 GiB total capacity; 35.21 GiB already 
allocated; 379.56 MiB free; 37.56 GiB reserved in total by PyTorch)  
```
So I tweaked the pipeline parallel to 1 to try bringing down the memory usage, and got the following.
```
RuntimeError: CUDA out of memory. Tried to allocate 21.26 GiB (GPU 0; 39.59 GiB total capacity; 21.26 GiB already 
allocated; 16.57 GiB free; 21.27 GiB reserved in total by PyTorch) 
```

**Comment by jamesthesnake** [comment]
Is this still happening?

**Comment by dongs0104** [comment]
what is different `1260000000` to `500000000`

**Comment by rehan243** [comment]
Are you using the latest version of Deepspeed? I ran into a similar CUDA OOM issue with a large model, and it turned out to be due to the `train_batch_size` not being properly set. In your config, I see you've set `train_micro_batch_size_per_gpu` to 1, but what's your `gradient_accumulation_steps` set to? I had to adjust that to avoid OOMs. For example, you can try adding this to your config: 
```python
"gradient_accumulation_steps": 4,
"train_batch_size": 4,
```
This effectively batches 4 micro-batches together before doing a weight update. I've found that this helps reduce memory usage significantly. By the way, what's your Deepspeed version - are you on v0.9.x or v0.10.x?

**Comment by rehan243** [comment]
I hit a similar CUDA OOM issue with a large model on 4x A100s, turned out it was due to the `train_micro_batch_size_per_gpu` being too high. You're using `pipe-parallel-size` of 1, so I'd check if your batch size is still too large - you've got `train_micro_batch_size_per_gpu` set to 1, which is good, but what's your `gradient_accumulation_steps` set to? 

Looking at your config, I'm guessing you're using Adam optimizer with a pretty low LR (0.97e-4). I've found that using `torch.cuda.empty_cache()` after loading the model can help, but that's more of a band-aid. To be honest, I'd try tweaking the optimizer settings or reducing the `seq-length` if possible. 
```python
import torch
# ... after loading model ...
torch.cuda.empty_cache()
```
Are you using the latest PyTorch version, btw?
